name: OWASP ZAP SCAN

on:
  push:
    branches:
      - master

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: OWASP Scan
    steps:
      # ZAP Scan
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          target: 'https://dev.eems-cac.me.uk/login'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-I -x report.xml'
      
      # Install Faraday Client
      - name: Download Faraday Client
        run: wget https://storage.googleapis.com/faraday-community/faraday-client_amd64.deb

      - name: Install Faraday Client
        run: sudo apt install ./faraday-client_amd64.deb

      - name: Create Credential File
        run: echo -e '{\n  "username":"faraday",\n  "password":"JzDFF9nJ7YF6" \n}' > cred.json

      - name: Start Faraday Client & Upload Report
        run: ls /home/runner/work/OWASP/.faraday

          # mv /home/runner/work/OWASP/OWASP/report.xml /home/.faraday/report/poc3-owasp-zap/
          # faraday-client --cli -w poc3-owasp-zap --report /home/.faraday/report/poc3-owasp-zap/report.xml --creds-file ./cred.json

      # # Upload ZAP Scan Report
      # - name: Upload Scan Report
      #   run: |
      #     mv ./report.xml /home/.faraday/report/poc3-owasp-zap/
      #     faraday-client --gui=nogui

      # # Configure AWS
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ap-northeast-1

      # # Copy to S3
      # - name: Copy files to S3 with the AWS CLI
      #   env:
      #     BUCKET_NAME: faraday-report
      #   run: |
      #     aws s3 sync ./report.xml s3://$BUCKET_NAME --delete
