name: OWASP

on:
  push:
    branches:
      - master

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: OWASP Scan
    steps:
      # # ZAP Scan
      # - name: Checkout
      #   uses: actions/checkout@v2
      #   with:
      #     ref: master

      # - name: ZAP Scan
      #   uses: zaproxy/action-baseline@v0.3.0
      #   with:
      #     target: 'https://dev.eems-cac.me.uk/login'
      #     rules_file_name: '.zap/rules.tsv'
      #     cmd_options: '-I -x report.xml'
      
      # Install Faraday Client
      - name: Download Faraday Client
        run: wget https://storage.googleapis.com/faraday-community/faraday-client_amd64.deb
      
      - name: Install Faraday Client
        run: sudo dpkg –i ./faraday-client_amd64.deb
      
      - name: Start Faraday Client
        run: |
          faraday-client --gui=nogui -w poc3-owasp-zap --login
          http://dev-poc3-loadblancer-903268067.ap-northeast-1.elb.amazonaws.com:5985/
          faraday
          JzDFF9nJ7YF6

      # Upload ZAP Scan Report
      - name: Upload Scan Report
        run: |
          mv ./report.xml /home/.faraday/report/poc3-owasp-zap/
          faraday-client --gui=nogui

      # # Configure AWS
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ap-northeast-1

      # # Copy to S3
      # - name: Copy files to S3 with the AWS CLI
      #   env:
      #     BUCKET_NAME: faraday-report
      #   run: |
      #     aws s3 sync ./report.xml s3://$BUCKET_NAME --delete
