name: OWASP

on:
  push:
    branches:
      - master

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: OWASP Scan
    steps:
      # ZAP Scan
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          target: 'https://dev.eems-cac.me.uk/login'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-I -x report.xml'

      # Configure AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      # Copy to S3
      - name: Copy files to S3 with the AWS CLI
        env:
          BUCKET_NAME: faraday-report
        run: |
          aws s3 sync ./ s3://$BUCKET_NAME --delete
