name: OWASP ZAP SCAN

on:
  push:
    branches:
      - master

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: OWASP Scan
    steps:
      # ZAP Scan
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          target: 'https://dev.eems-cac.me.uk/login'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-I -x report.xml'
      
      # Install Faraday Client
      - name: Download Faraday Client
        run: wget https://storage.googleapis.com/faraday-community/faraday-client_amd64.deb

      - name: Install Faraday Client
        run: sudo apt install ./faraday-client_amd64.deb

      - name: Create Credential File
        run: echo -e '{\n  "username":"faraday",\n  "password":"JzDFF9nJ7YF6" \n}' > cred.json

      # Upload Scan Report 
      - name: Start Faraday Client & Upload Scan Report
        run: echo ${{ secrets.FARADAY_SERVER_URL }} | faraday-client --cli -w poc3-owasp-zap --report ./report.xml --cert ./cred.json
