name: OWASP

on:
  push:
    branches:
      - master

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: OWASP Scan
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          target: 'https://dev.eems-cac.me.uk/login'
          cmd_options: '-I'

  trigger-katalon-test:
    name: Execute Automation Test
    runs-on: ubuntu-latest
    needs: zap_scan
    steps: 
    - name: trigger katalon test
      env: 
        TOKEN_NAME: 117692ba38a05fb43686487552e1eba637
      run: |
        curl -gv --insecure http://dev-poc3-loadblancer-903268067.ap-northeast-1.elb.amazonaws.com/jenkins/job/katalonExplore/buildWithParameters?token=${TOKEN_NAME}