name: OWASP ZAP SCAN

on:
  push:
    branches:
      - master

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: OWASP Scan
    steps:
      # ZAP Scan
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          target: 'https://dev.eems-cac.me.uk/login'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-I -x report.xml'
      
      # Install Faraday Client
      - name: Download Faraday Client
        run: wget https://storage.googleapis.com/faraday-community/faraday-client_amd64.deb

      - name: Install Faraday Client
        run: sudo apt install ./faraday-client_amd64.deb
      
      - name: Install Expect
        run: sudo apt install expect

      # - name: Create Credential File
      #   run: echo -e '{\n  "username":"faraday",\n  "password":"JzDFF9nJ7YF6" \n}' > cred.json

      # Upload Scan Report 
      - name: Start Faraday Client & Upload Scan Report
        run: |
          expect -c "spawn bash -c \"echo 'http://dev-poc3-loadblancer-903268067.ap-northeast-1.elb.amazonaws.com:5985/\n' | faraday-client --cli -w poc3-test --report ./report.xml --login\" ; expect \"Username (press enter for faraday):\" ; send \"faraday\n\" ; expect \"Password:\" ; send \"KJzDFF9nJ7YF6\n\" ; interact "
          cat ./report.xml
        # run: echo -e '${{ secrets.FARADAY_SERVER_URL }} \n ${{ secrets.FARADAY_USERNAME }} \n ${{ secrets.FARADAY_PASSWORD }}' | faraday-client --cli -w poc3-owasp-zap --report ./report.xml --cert ./cred.json
