name: OWASP

on:
  push:
    branches:
      - master

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: OWASP Scan
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          target: 'https://dev.eems-cac.me.uk/login'
          cmd_options: '-I'
